export enum CoreManagerMethods {
  infoCoreVersion = 'info.coreVersion',
  infoCoreStatus = 'info.coreStatus',
  infoNextForgingSlot = 'info.nextForgingSlot',
  infoBlockchainHeight = 'info.blockchainHeight',
  infoCurrentDelegate = 'info.currentDelegate',
  infoLastForgedBlock = 'info.lastForgedBlock',
  logArchived = 'log.archived',
  processList = 'process.list',
  processRestart = 'process.restart',
  processStop = 'process.stop',
  configurationGetEnv = 'configuration.getEnv',
  configurationGetPlugins = 'configuration.getPlugins',
  configurationUpdatePlugins = 'configuration.updatePlugins',
}
