name: Publish Artifacts

on:
  push:
    branches:
      - "feat/prod-pipeline-output-hashes"

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run electron:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate Checksums for DMG
        run: shasum -a 256 release/protokol-manager.dmg

      - name: VirusTotal Scan for DMG
        run: |
          UPLOAD_URL=$(curl -s --location --url 'https://www.virustotal.com/vtapi/v2/file/scan/upload_url?apikey=${{ secrets.VIRUSTOTAL_API_KEY }}' | jq -r .upload_url)
          curl -s --url "$UPLOAD_URL" --form 'apikey=${{ secrets.VIRUSTOTAL_API_KEY }}' --form 'file=@release/protokol-manager.dmg' | jq -r .permalink

      - name: Determine the release version
        id: derive_release_version
        run: |
          RELEASE_VERSION=$(cat package.json | jq -r '.version')
          echo "::set-output name=version::${RELEASE_VERSION}"

      - name: Package artifacts
        run: |
          mkdir artifact-macos
          mv release/protokol-manager.dmg artifact-macos/
          mv release/latest-mac.yml artifact-macos/

      - uses: actions/upload-artifact@v2
        name: Upload macos dmg artifact
        with:
          name: protokol-manager.dmg
          path: artifact-macos/protokol-manager.dmg
          if-no-files-found: error


  create-release:
    runs-on: ubuntu-latest
    needs: [ build-macos ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine the release version
        id: derive_release_version
        run: |
          RELEASE_VERSION=$(cat package.json | jq -r '.version')
          echo "::set-output name=version::${RELEASE_VERSION}"

      - name: Changelog version
        id: changelog_version
        run: |
          CHANGELOG_VERSION=$(echo '${{ steps.derive_release_version.outputs.version }}' | tr -d .)
          echo "::set-output name=version::${CHANGELOG_VERSION}"

      - uses: actions/download-artifact@v2
        with:
          path: protokol-manager.dmg
          name: protokol-manager_${{ steps.derive_release_version.outputs.version }}.dmg

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.derive_release_version.outputs.version }}
          name: Version ${{ steps.derive_release_version.outputs.version }}
          body: |
            Changelog:
            [${{ steps.derive_release_version.outputs.version }} changelog](https://github.com/protokol/protokol-manager/blob/feat/release-pipeline/CHANGELOG.md#v${{ steps.changelog_version.outputs.version }})
          artifacts: "protokol-manager_*"
          draft: true
          prerelease: false
